import pyautogui, keyboard

pyautogui.PAUSE = 2.5
pyautogui.moveTo(0, 20)

pyautogui.click(x=1862, y=122, clicks=2, button='left')
pyautogui.click(x=-1242, y=53, clicks=2, button='left')
pyautogui.typewrite('https://www.instagram.com \n', interval=0.05)

pyautogui.click(x=-942, y=426, clicks=1, button='left')
pyautogui.click(x=-1124, y=99, clicks=1, button='left')
pyautogui.hotkey('altright', '3', interval=0.1)
pyautogui.typewrite('ai', interval=0.05)
pyautogui.click(x=-1111, y=359, clicks=1, button='left')
pyautogui.click(x=-1478, y=777, clicks=1, button='left')
pyautogui.click(x=-960, y=673, clicks=1, button='left')
pyautogui.moveTo(x=-993, y=341, duration=1)

pyautogui.scroll(-600)
pyautogui.click()
pyautogui.scroll(-70)
pyautogui.click()
pyautogui.scroll(-280)
pyautogui.click()
pyautogui.scroll(-70)
pyautogui.click()
pyautogui.scroll(-155)
pyautogui.click()
pyautogui.scroll(-210)
pyautogui.click()
pyautogui.scroll(-70)
pyautogui.click()
pyautogui.scroll(-210)
pyautogui.click()
pyautogui.scroll(-145)
pyautogui.click()
pyautogui.scroll(-70)
pyautogui.click()
pyautogui.scroll(-70)
pyautogui.click()
pyautogui.scroll(-210)
pyautogui.click()
pyautogui.scroll(-70)
pyautogui.click()
pyautogui.scroll(-80)
pyautogui.click()
pyautogui.scroll(-140)
